After altering code to return inverted and non-inverted distances it was seen that machine learning models performed worse on data generated from simulations with the new code for distance calculations.

Closer inspection between the original code and the new code data revealed the distance values are different. Which is shown below.

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
df1 = pd.read_csv("data/comparison/diffusion_data_old.csv")
df2 = pd.read_csv("data/comparison/diffusion_data_old_comparison.csv")

In [9]:
df2 = df2.drop(['l0', 'l1', 'l2', 'l3', 'l4', 'l5', 'l6', 'l7', 'bo0', 'bo1',
       'bo2', 'bo3', 'bo4', 'bo5', 'bo6', 'bo7'], axis=1)

In [10]:
df1.describe() ##original inverse distance calculation method

l0           l1           l2           l3           l4  \
count  5400.000000  5400.000000  5400.000000  5400.000000  5400.000000   
mean      0.586997     0.615485     0.647142     0.682559     0.722782   
std       0.038325     0.043146     0.047747     0.051800     0.055658   
min       0.477690     0.480583     0.500006     0.515954     0.532420   
25%       0.559704     0.584476     0.613492     0.646172     0.683860   
50%       0.583645     0.612503     0.644045     0.680084     0.721079   
75%       0.611562     0.643451     0.677990     0.716322     0.762788   
max       0.748136     0.778980     0.833226     0.881693     0.900790   

                l5           l6           l7          vol  n_neighbours  \
count  5400.000000  5400.000000  5400.000000  5400.000000        5400.0   
mean      0.768064     0.814929     0.867676     0.202119          53.0   
std       0.057432     0.054830     0.046864     0.017690           0.0   
min       0.564331     0.608762     0.654258     0.125780          53.0   
25%       0.728480     0.777972     0.841611     0.190213          53.0   
50%       0.769957     0.820456     0.876930     0.201926          53.0   
75%       0.809833     0.857114     0.900595     0.214180          53.0   
max       0.920324     0.933467     0.974033     0.260716          53.0   

                Ds  
count  5400.000000  
mean      0.388897  
std       0.026151  
min       0.303290  
25%       0.371233  
50%       0.388729  
75%       0.406847  
max       0.473188

In [11]:
df2.describe() #new distance calculation method

l0_inv       l1_inv       l2_inv       l3_inv       l4_inv  \
count  5400.000000  5400.000000  5400.000000  5400.000000  5400.000000   
mean      0.304822     0.300134     0.294986     0.289643     0.283756   
std       0.007565     0.007536     0.007398     0.007378     0.007365   
min       0.278714     0.275043     0.270550     0.266092     0.259257   
25%       0.299560     0.294902     0.289809     0.284563     0.278681   
50%       0.304795     0.299968     0.294793     0.289302     0.283549   
75%       0.309821     0.305201     0.299841     0.294441     0.288622   
max       0.337646     0.331201     0.326978     0.324968     0.309208   

            l5_inv       l6_inv       l7_inv          vol  n_neighbours  \
count  5400.000000  5400.000000  5400.000000  5400.000000        5400.0   
mean      0.277136     0.268607     0.253139     0.202119          53.0   
std       0.007692     0.008568     0.011126     0.017690           0.0   
min       0.252464     0.244788     0.222960     0.125780          53.0   
25%       0.271828     0.262514     0.245152     0.190213          53.0   
50%       0.277037     0.268636     0.253215     0.201926          53.0   
75%       0.282232     0.274468     0.260900     0.214180          53.0   
max       0.307038     0.305929     0.288665     0.260716          53.0   

                Ds  
count  5400.000000  
mean      0.388897  
std       0.026151  
min       0.303290  
25%       0.371233  
50%       0.388729  
75%       0.406847  
max       0.473188

In [12]:
df1.head() #distance increase from l0-l1-l2

l0        l1        l2        l3        l4        l5        l6  \
0  0.563190  0.565949  0.580143  0.707842  0.773975  0.834769  0.884115   
1  0.575812  0.590612  0.632228  0.649492  0.685031  0.731453  0.744061   
2  0.564883  0.575887  0.607135  0.613226  0.648257  0.651667  0.694666   
3  0.566483  0.583332  0.648028  0.700093  0.725940  0.791908  0.866125   
4  0.552615  0.566483  0.706214  0.773975  0.827710  0.847720  0.905372   

         l7       vol  n_neighbours        Ds  
0  0.888794  0.200455          53.0  0.367946  
1  0.888794  0.206035          53.0  0.405260  
2  0.906113  0.216181          53.0  0.411686  
3  0.869910  0.192773          53.0  0.387032  
4  0.916870  0.192975          53.0  0.346245

In [13]:
df2.head() #distance decrease from l0-l1-l2

l0_inv    l1_inv    l2_inv    l3_inv    l4_inv    l5_inv    l6_inv  \
0  0.327585  0.306842  0.296504  0.273028  0.272212  0.272194  0.271903   
1  0.307693  0.296377  0.290680  0.283923  0.283177  0.278030  0.259357   
2  0.295189  0.291421  0.290889  0.286601  0.270011  0.268861  0.265629   
3  0.297522  0.294896  0.291925  0.290213  0.288542  0.286441  0.278636   
4  0.292926  0.291168  0.287640  0.278957  0.278711  0.269904  0.267637   

     l7_inv       vol  n_neighbours        Ds  
0  0.239305  0.200455          53.0  0.367946  
1  0.249806  0.206035          53.0  0.405260  
2  0.251295  0.216181          53.0  0.411686  
3  0.266408  0.192773          53.0  0.387032  
4  0.266100  0.192975          53.0  0.346245

The method of calculating inverse distances differs between df1 and df2.

For df1 calculation:
1) Distance values are inverted
2) Inverse distance sorted in ascending order
3) Last n values taken

For df2 calculation:
1) Distance values are sorted
2) Distance values are inverted
3) Last n values taken

In [14]:
test = np.asarray([[4,5,3,1,2],
                   [0.3, 0.6, 0.2,0.4, 0.1]])

In [15]:
goal = np.sort(1/test)

In [16]:
test

array([[4. , 5. , 3. , 1. , 2. ],
       [0.3, 0.6, 0.2, 0.4, 0.1]])

In [17]:
1/test

array([[ 0.25      ,  0.2       ,  0.33333333,  1.        ,  0.5       ],
       [ 3.33333333,  1.66666667,  5.        ,  2.5       , 10.        ]])

Applying original method to test sample.

In [18]:
np.sort(1/test)[:,:] #invert numbers, sort ascending #ORIGINAL METHOD DF1
#this has the effect of putting non inverted values in descending order
#i.e. distances sorted from largest to smallest
#this means inverted values are in ascending order
#taking last n points then returns the distances to closest n points 
#small values which become large when inverted

array([[ 0.2       ,  0.25      ,  0.33333333,  0.5       ,  1.        ],
       [ 1.66666667,  2.5       ,  3.33333333,  5.        , 10.        ]])

Applying altered method to test sample.

In [19]:
1/np.sort(test)[:,:] #sort ascending, invert numbers #NEW METHOD DF2
# has the effect of putting non inverted values in ascending order
#i.e. distances sorted from smallest to largest
#this means inverted values are in descending order
#taking last n points returns the distance to furthest n points
#large values (which are small when inverted)

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ],
       [10.        ,  5.        ,  3.33333333,  2.5       ,  1.66666667]])

DF1 Data

In [20]:
df1.iloc[0].values[:-3] #inverted distances

array([0.56319023, 0.56594864, 0.58014344, 0.70784193, 0.77397472,
       0.83476917, 0.88411503, 0.88879414])

In [21]:
1/df1.iloc[0].values[:-3] #normal distances

array([1.77559898, 1.76694477, 1.72371164, 1.41274479, 1.29203187,
       1.19793595, 1.13107454, 1.12511993])

Above we see the inverted values are larger than df2, but the normal distances are smaller.

DF2 Data

In [22]:
df2.iloc[0].values[:-3] #inverted distances

array([0.32758493, 0.30684164, 0.29650353, 0.27302801, 0.2722123 ,
       0.27219435, 0.2719027 , 0.2393047 ])

In [23]:
1/df2.iloc[0].values[:-3] #normal distances

array([3.05264348, 3.25901004, 3.37264117, 3.66262791, 3.67360334,
       3.67384549, 3.67778623, 4.17877287])

Above we see the inverted values are smaller than DF1 but the normal distances are larger.


Using data by the new calculation method introduces an error which returns the distances to the furthest points which are treated as the n closest neighbours. The original method is correct as it returns the distnces to the n closest neighbours. It makes sense then that machine learning models perform worse when trained on DF2 as there is less relevant info in the included distance information.

To fix this:

In [24]:
#inverted distances should return
goal[:,-2:]

array([[ 0.5,  1. ],
       [ 5. , 10. ]])

In [25]:
#non-inverted distances should return:
1/goal[:,-2:]

array([[2. , 1. ],
       [0.2, 0.1]])

In [26]:
test

array([[4. , 5. , 3. , 1. , 2. ],
       [0.3, 0.6, 0.2, 0.4, 0.1]])

In [29]:
#getting inverted distances
np.sort(1/test)[:,-2:]

array([[ 0.5,  1. ],
       [ 5. , 10. ]])

In [30]:
#getting normal distances
-np.sort(-test)[:,-2:]

array([[2. , 1. ],
       [0.2, 0.1]])

In [48]:
np.sort(test)[:,:2]

array([[1. , 2. ],
       [0.1, 0.2]])

In [57]:
-np.sort(-1/test)[:,:2]

array([[ 1. ,  0.5],
       [10. ,  5. ]])